### ISSUE TITLE
Add PyMem_RawMalloc and friends

### ISSUE THREAD

**Issue by jonathanunderwood** [encukou/py3c#10]
In python 3.4 `PyMem_RawMalloc`, `PyMem_RawCalloc`, `PyMem_RawRealloc`, and `PyMem_RawFree` were added which allow memory management without requiring the GIL to be held (as opposed to the non-Raw versions). It would be great if those wrappers were available via py3c for earlier Python versions.

[https://github.com/python/cpython/blob/master/Include/pymem.h#L15-L18](https://github.com/python/cpython/blob/master/Include/pymem.h#L15-L18)

**Comment by encukou** [comment]
This is a good idea. I'll add it when I find time.

It should go into a new header for 3.4+ shims, which should be included from the main `py3c.h`.
