### ISSUE TITLE
inline isn't defined on (some versions of) visual studio

### ISSUE THREAD

**Issue by jonathanunderwood** [encukou/py3c#11]
With the Visual Studio compiler, at least for older versions often usedd to build extensions for earlier versions of Python (eg 2.6), "inline" isn't defined, but __inline is. This causes a compilation error:

```
py3c\py3c/compat.h(76) : error C2054: expected '(' to follow 'inline'
```
There's a fairly simple fix:

```C
#if defined(_WIN32) && defined(_MSC_VER)
#define inline __inline
#endif
```

**Comment by encukou** [comment]
Interesting, thanks for the report!
In that case I'd rather just remove `inline` from py3c.
