### ISSUE TITLE
PyPi package doesn't install pkg-config file

### ISSUE THREAD

**Issue by jonathanunderwood** [encukou/py3c#25]
As per title - the PyPi package doesn't include the pkgconfig file.

**Comment by encukou** [comment]
IMO, pkgconfig is meant for system-wide installs. Wheels don't support that very well. You're better off using a system package (`rpm`, `deb`, etc.) if you need pkg-config.

(I'd be happy to be proven wrong here, though.)

**Comment by jonathanunderwood** [comment]
Yeah. Agreed. But this and #24 together basically make the PyPi package unusable from the perspective of packaging a module that depends on the Py3c headers. The PyPi package arguably makes it a bit easier to grab the headers and copy them into a project, but I can't do things like `install_requires=[py3c]` in order to ensure that the headers are available at install time. I'll close this.
