### ISSUE TITLE
Add Py_UNUSED shim

### ISSUE THREAD

**Issue by jonathanunderwood** [encukou/py3c#9]
`Py_UNUSED` is defined from Python 3.4 onwards, and is useful for squashing warnings about unused arguments. It's be good to add a shim for backwards compatibility for this to py3c. Suggest:

```C
#ifndef Py_UNUSED		/* This is already defined for Python 3.4 onwards */
#ifdef __GNUC__
#define Py_UNUSED(name) _unused_ ## name __attribute__((unused))
#else
#define Py_UNUSED(name) _unused_ ## name
#endif
#endif
```

**Comment by encukou** [comment]
This is a good idea. I'll add it when I find time.

It should go into a new header for 3.4+ shims, which should be included from the main `py3c.h`.

**Comment by encukou** [comment]
I just found the `Py_UNUSED` macro is undocumented. I've opened [an issue](http://bugs.python.org/issue29179) about this, and if Python developers agree, I'll document it in CPython and add the shim to py3c.

**Comment by jonathanunderwood** [comment]
Looks like this can be closed now, right?
